<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p>&nbsp;</p>
        </div>
        <div class="col-md-8 offset-2">
            <div id="progressbar" style="border:1px solid #ccc; border-radius: 10px; "></div>
            <br>
            <div id="information"></div>
        </div>
    </div>
</div>$percent = intval($i / $nomRows * 100) . "%"; //$percentCrud =$NumeroPorcent/$numero100 * 100; if ($percent < 20) { echo '
<script>
        parent.document.getElementById("progressbar").innerHTML="<div style=\"width:' . $percent . ';background:linear-gradient(to bottom, #FF5722 0%,#9C27B0 100%); height:35px;\">&nbsp;</div>";               parent.document.getElementById("information").innerHTML="<div style=\"text-align:center; font-weight:bold\">' . $percent . ' procesado...</div>";</script>' ;      } elseif ($percent < 40) {        echo '<script>               parent.document.getElementById("progressbar").innerHTML="<div style=\"width:' . $percent . ';background:linear-gradient(to bottom, #9c27b078 0%,#FF5722 100%); height:35px;\">&nbsp;</div>";               parent.document.getElementById("information").innerHTML="<div style=\"text-align:center; font-weight:bold\">' . $percent . ' procesado...</div>";</script>' ;      } elseif ($percent < 60) {        echo '<script>               parent.document.getElementById("progressbar").innerHTML="<div style=\"width:' . $percent . ';background:linear-gradient(to bottom, #d05be478 0%,#ff9800 100%);height:35px;\">&nbsp;</div>";               parent.document.getElementById("information").innerHTML="<div style=\"text-align:center; font-weight:bold\">' . $percent . ' procesado...</div>";</script>' ;      } elseif ($percent < 60) {        echo '<script>               parent.document.getElementById("progressbar").innerHTML="<div style=\"width:' . $percent . ';background:linear-gradient(to bottom, #4caf50ab 0%,#CDDC39 100%);height:35px;\">&nbsp;</div>";               parent.document.getElementById("information").innerHTML="<div style=\"text-align:center; font-weight:bold\">' . $percent . ' procesado...</div>";</script>' ;      } elseif ($percent < 80) {        echo '<script>               parent.document.getElementById("progressbar").innerHTML="<div style=\"width:' . $percent . ';background:linear-gradient(to bottom, #00bcd49e 0%,#8BC34A 100%);height:35px;\">&nbsp;</div>";               parent.document.getElementById("information").innerHTML="<div style=\"text-align:center; font-weight:bold\">' . $percent . ' procesado...</div>";</script>' ;      } else {        echo '<script>               parent.document.getElementById("progressbar").innerHTML="<div style=\"width:' . $percent . ';background:linear-gradient(to bottom, #4caf505e 0%,#15b31c 100%);height:35px;\">&nbsp;</div>";               parent.document.getElementById("information").innerHTML="<div style=\"text-align:center; font-weight:bold\">' . $percent . ' procesado...</div>";</script>' ;      }      ob_flush();      flush();